### ISSUE TITLE
Add function for textual representation of values

### ISSUE THREAD

**Issue by dirkjanfaber** [Chris927/dbus-victron-virtual#2]
In order to switch between the textual and non-textual representation (using the letter `t` in `dbus-spy`), ideally a function should be added to the interface description, probably around [here](https://github.com/Chris927/dbus-victron-virtual/blob/main/src/index.js#L58). 

This is needed for things like converting the integer representation of the ProductId to the hex value. 
So there the function would need to return `value.toString(16)`.

For things like the temperature, the conversion would be a function that does `${value.toFixed(1)}C`

**Comment by Chris927** [comment]
I've implemented the option to format the text representation in [this commit](https://github.com/Chris927/dbus-victron-virtual/commit/800a5f7a6fda392ee1004ed09233ad8e57ff7c8e). The unit tests included in the commit demonstrate how to use it.

Let me know if this solves this need.

**Comment by dirkjanfaber** [comment]
Ok, got it running via https://github.com/dirkjanfaber/dbus-victron-virtual-test/tree/faberd/virtual-thermometer 

One thing that doesn't seem to work, is setting the type to `d` on line [55](https://github.com/dirkjanfaber/dbus-victron-virtual-test/blob/faberd/virtual-thermometer/index.js#L55), which gives me an uncaught exception:
```
            triggerUncaughtException(err, true /* fromPromise */);
```

~~Not sure how to circumvent that.~~. That was missing the update that adds support for `d`

**Comment by dirkjanfaber** [comment]
Got a bit further and a good working example (outside of Node-RED):

```
root@ekrano:~# dbus -y com.victronenergy.temperature.ruuvi_dd4240ee1474 /DeviceInstance GetValue
value = 25
root@ekrano:~# dbus -y com.victronenergy.temperature.virtual_dfa /DeviceInstance GetValue
Traceback (most recent call last):
  File "/usr/bin/dbus", line 374, in <module>
    ret = obj.object.get_dbus_method(method.name, iface.name)(*args)
AttributeError: 'NoneType' object has no attribute 'name'
```
Which probably should become a new issue: Add `GetValue()`

Feel free to close this issue, I'll open a new one for that.

**Comment by Chris927** [comment]
Resolving this, continuing on #3 .
